export const ADD_USER = "ADD_USER";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const CLEAR_USER = "CLEAR_USER";
export const CLEAR_BUCKET_USER = "CLEAR_BUCKET_USER";
export const ADD_BUY_PRODUCT = "ADD_BUY_PRODUCT";
export const DELETE_USER_PRODUCT = "DELETE_USER_PRODUCT";

export const GET_PRODUCTS_LIST = "GET_PRODUCTS_LIST";
export const GET_PRODUCTS_LIST_SUCCESS = "GET_PRODUCTS_LIST_SUCCESS";

export const ADD_LIKE_PRODUCT = "ADD_LIKE_PRODUCT";
export const ADD_LIKE_PRODUCT_FAIL = "ADD_LIKE_PRODUCT_FAIL";
export const ADD_LIKE_PRODUCT_SUCCESS = "ADD_LIKE_PRODUCT_SUCCESS";
export const DELETE_LIKE_PRODUCT = "DELETE_LIKE_PRODUCT";

export const GET_PRODUCTS_LIKE_INITIAL = "GET_PRODUCTS_LIKE_INITIAL";
export const GET_PRODUCTS_LIKE_FAIL = "GET_PRODUCTS_LIKE_FAIL";
export const GET_PRODUCTS_LIKE_SUCCESS = "GET_PRODUCTS_LIKE_SUCCESS";

export const GET_PRODUCTS_BUY_INITIAL = "GET_PRODUCTS_BUY_INITIAL";
export const GET_PRODUCTS_BUY_FAIL = "GET_PRODUCTS_BUY_FAIL";
export const GET_PRODUCTS_BUY_SUCCESS = "GET_PRODUCTS_BUY_SUCCESS";
export const ADD_PRICE_PRODUCT = "ADD_PRICE_PRODUCT";
export const DELETE_BUCKET_PRODUCT = "DELETE_BUCKET_PRODUCT";
export const MINUS_PRICE_PRODUCT = "MINUS_PRICE_PRODUCT";
export const CLEAR_BUCKET = "CLEAR_BUCKET";

export const GET_NEWS = "GET_NEWS";
export const GET_NEWS_FAIL = "GET_NEWS_FAIL";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_SUCCESS_MORE = "GET_NEWS_SUCCESS_MORE";
export const MORE_NEWS = "MORE_NEWS";

export const GET_PRODUCTS_LIST_SEARCH_SUCCESS = "GET_PRODUCTS_LIST_SEARCH_SUCCESS";
export const CLEAR_PRODUCTS_LIST = "CLEAR_PRODUCTS_LIST";
