export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const ADD_USER = "ADD_USER";
export const CLEAR_USER = "CLEAR_USER";

export const ADD_INIT = "ADD_INIT";
export const ADD_INIT_FAIL = "ADD_INIT_FAIL";
export const CLEAR_ADMIN = "CLEAR_ADMIN";

export const ADD_ROLE = "ADD_ROLE";
export const DELETE_ROLE_FAIL = "DELETE_ROLE_FAIL";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";

export const MANAGER_INIT = "MANAGER_INIT";
export const MANAGER_INIT_FAIL = "MANAGER_INIT_FAIL";

export const CLEAR_MANAGER = "CLEAR_MANAGER";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";

export const ADD_SUB_CATEGORY = "ADD_SUB_CATEGORY";
export const ADD_SUB_CATEGORY_FAIL = "ADD_SUB_CATEGORY_FAIL";
export const ADD_SUB_CATEGORY_SUCCESS = "ADD_SUB_CATEGORY_SUCCESS";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const ADD_COUNT = "ADD_COUNT";
export const ADD_COUNT_SUCCESS = "ADD_COUNT_SUCCESS";
export const ADD_COUNT_FAIL = "ADD_COUNT_FAIL";

export const CHANGE_PRODUCT = "CHANGE_PRODUCT";
export const CHANGE_PRODUCT_FAIL = "CHANGE_PRODUCT_FAIL";
export const CHANGE_PRODUCT_SUCCESS = "CHANGE_PRODUCT_SUCCESS";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";

export const DELETE_SUB_CATEGORY = "DELETE_SUB_CATEGORY";
export const DELETE_SUB_CATEGORY_FAIL = "DELETE_SUB_CATEGORY_FAIL";
export const DELETE_SUB_CATEGORY_SUCCESS = "DELETE_SUB_CATEGORY_SUCCESS";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
